services:
  django-web:
    build:
      args:
        - DJANGO_DEBUG
    container_name: django-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: