# Generated by Django 5.1 on 2024-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0002_board_changed_board_created_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
