# Generated by Django 5.1 on 2024-09-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0003_alter_board_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-changed', 'created']},
        ),
    ]
